#! /bin/sh

sxhkd &

#bspc monitor HDMI-1-1 -d II III VI VII
#bspc monitor eDP-1-1 -d I IV V

#bspc monitor -d IV V VI VII VIII IX X
#bspc monitor eDP-1-1 -d I II III
#bspc monitor HDMI-1-1 -d IV V VI
# bspc monitor HDMI-1-1 I II II IV
# bspc monitor -d eDP-1-1 I II III IV
bspc monitor -d HDMI-1-1 I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true
