#!/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# bspc config active_border_color "#333333"

bspc config border_width         2
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zim desktop='^9' state=tiled follow=off
bspc rule -a korganizer desktop='^8' state=tiled follow=off
bspc rule -a dia desktop='^7' state=tiled follow=off
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true
bspc rule -a lxqt-openssh-askpass state=floating

#feh --bg-center --bg-scale ~/img/wallpaper.jpg
feh --bg-center --bg-scale $HOME/img/background/background-dark-bird.jpg
bspc config focused_border_color "#aa2222"

bspc config external_rules_command "$(which external_rules)"
